name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main
        
        with:
          channel-priority: disabled
          cache-downloads: true
          environment-name: sparsecca
          environment-file: environment.yml

      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: pip-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ env.pythonLocation }}-

      - name: Activate environment
        run: |
          eval "$(micromamba shell hook --shell=bash)"
          micromamba activate sparsecca

      - name: Print pip list
        run: pip list

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install codecov

      - name: Install dependencies
        run: |
          pip install ".[dev,test]"

      - name: Test
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
          DISPLAY: :42
        run: |
          pytest -v --cov --color=yes

      - name: Upload coverage
        env:
          CODECOV_NAME: ${{ matrix.python }}-${{ matrix.os }}
        run: |
          codecov --required --flags=unittests
